// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EMAnext
Rcpp::NumericVector EMAnext(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double tau);
RcppExport SEXP _RcppUTS_EMAnext(SEXP timesSEXP, SEXP valuesSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(EMAnext(times, values, tau));
    return rcpp_result_gen;
END_RCPP
}
// EMAlast
Rcpp::NumericVector EMAlast(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double tau);
RcppExport SEXP _RcppUTS_EMAlast(SEXP timesSEXP, SEXP valuesSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(EMAlast(times, values, tau));
    return rcpp_result_gen;
END_RCPP
}
// EMAlinear
Rcpp::NumericVector EMAlinear(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double tau);
RcppExport SEXP _RcppUTS_EMAlinear(SEXP timesSEXP, SEXP valuesSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(EMAlinear(times, values, tau));
    return rcpp_result_gen;
END_RCPP
}
// SMAnext
Rcpp::NumericVector SMAnext(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double widthbefore, const double widthafter);
RcppExport SEXP _RcppUTS_SMAnext(SEXP timesSEXP, SEXP valuesSEXP, SEXP widthbeforeSEXP, SEXP widthafterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type widthbefore(widthbeforeSEXP);
    Rcpp::traits::input_parameter< const double >::type widthafter(widthafterSEXP);
    rcpp_result_gen = Rcpp::wrap(SMAnext(times, values, widthbefore, widthafter));
    return rcpp_result_gen;
END_RCPP
}
// SMAlast
Rcpp::NumericVector SMAlast(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double widthbefore, const double widthafter);
RcppExport SEXP _RcppUTS_SMAlast(SEXP timesSEXP, SEXP valuesSEXP, SEXP widthbeforeSEXP, SEXP widthafterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type widthbefore(widthbeforeSEXP);
    Rcpp::traits::input_parameter< const double >::type widthafter(widthafterSEXP);
    rcpp_result_gen = Rcpp::wrap(SMAlast(times, values, widthbefore, widthafter));
    return rcpp_result_gen;
END_RCPP
}
// SMAlinear
Rcpp::NumericVector SMAlinear(Rcpp::DatetimeVector times, Rcpp::NumericVector values, const double widthbefore, const double widthafter);
RcppExport SEXP _RcppUTS_SMAlinear(SEXP timesSEXP, SEXP valuesSEXP, SEXP widthbeforeSEXP, SEXP widthafterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type widthbefore(widthbeforeSEXP);
    Rcpp::traits::input_parameter< const double >::type widthafter(widthafterSEXP);
    rcpp_result_gen = Rcpp::wrap(SMAlinear(times, values, widthbefore, widthafter));
    return rcpp_result_gen;
END_RCPP
}
// utsExample
void utsExample();
RcppExport SEXP _RcppUTS_utsExample() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    utsExample();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppUTS_EMAnext", (DL_FUNC) &_RcppUTS_EMAnext, 3},
    {"_RcppUTS_EMAlast", (DL_FUNC) &_RcppUTS_EMAlast, 3},
    {"_RcppUTS_EMAlinear", (DL_FUNC) &_RcppUTS_EMAlinear, 3},
    {"_RcppUTS_SMAnext", (DL_FUNC) &_RcppUTS_SMAnext, 4},
    {"_RcppUTS_SMAlast", (DL_FUNC) &_RcppUTS_SMAlast, 4},
    {"_RcppUTS_SMAlinear", (DL_FUNC) &_RcppUTS_SMAlinear, 4},
    {"_RcppUTS_utsExample", (DL_FUNC) &_RcppUTS_utsExample, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppUTS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
