# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The UTS library by Andreas Eckner provides algorithms for unevenly
#' spaced time-series data.  This package brings a few of them to R.
#' The functions describe here offer exponentially-decaying weighted moving
#' average, or EMA, for short. Three variants are provides considering
#' the last or next observation relative to time \sQuote{t}, as well as
#' linear interpolation between them.
#' @title EMA functions for unevenly spaced time series
#' @param times A Datetime vector
#' @param values A numeric vector
#' @param tau A double with the decay factor
#' @return A numeric vector with EMA-weighted values.
#' package at the given position is available.
#' @author Dirk Eddelbuettel for the package, Andreas Eckner for the
#' underlying code.
#' @examples
#' if (requireNamespace("xts", quietly=TRUE)) {
#'     suppressMessages(library(xts))
#'     times <- ISOdatetime(2010, 1, 2, 8, 30, 0) + c(0, 1.0, 1.2, 2.3, 2.9, 5.0)
#'     values <- seq(0, 10, by=2)
#'     plot(xts(values, order.by=times), type="b",
#'          main="Series and last/next/linear EMAs")
#'     lines(xts(EMAlast(times,values, 1),  values, order.by=times),
#'           type="b", col="lightblue")
#'     lines(xts(EMAnext(times,values, 1),  values, order.by=times),
#'           type="b", col="darkblue")
#'     lines(xts(EMAlinear(times,values, 1),  values, order.by=times),
#'           type="b", col="mediumblue")
#'     addLegend("topleft", legend.names=c("series", "EMAlast", "EMAnext", "EMAlinear"),
#'               lty=rep(1,4), lwd=rep(1,4),
#'               col=c("black", "lightblue", "darkblue", "mediumblue"))
#' }
EMAnext <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAnext`, times, values, tau)
}

#' @rdname EMAnext
EMAlast <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAlast`, times, values, tau)
}

#' @rdname EMAnext
EMAlinear <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAlinear`, times, values, tau)
}

#' The UTS library by Andreas Eckner provides algorithms for unevenly
#' spaced time-series data.  This package brings a few of them to R.
#' The functions describe here offer various rolling operators.
#' @title Rolling operations functions for irregularly spaced time series
#' @param times A Datetime vector
#' @param values A numeric vector
#' @param widthbefore A double with the preceding observation width
#' @param widthafter A double with the subsequent observation width
#' @param moment A double with the requested moment.
#' @return A numeric vector with the corresponding result.
#' @author Dirk Eddelbuettel for the package, Andreas Eckner for the
#' underlying code.
rollingCentralMoment <- function(times, values, widthbefore, widthafter, moment) {
    .Call(`_RcppUTS_rollingCentralMoment`, times, values, widthbefore, widthafter, moment)
}

#' @rdname rollingCentralMoment
rollingMax <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingMax`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingMean <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingMean`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingMedian <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingMedian`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingMin <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingMin`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingNobs <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingNobs`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingProduct <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingProduct`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingSD <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingSD`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingSum <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingSum`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingSumStable <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingSumStable`, times, values, widthbefore, widthafter)
}

#' @rdname rollingCentralMoment
rollingVar <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_rollingVar`, times, values, widthbefore, widthafter)
}

#' The UTS library by Andreas Eckner provides algorithms for unevenly
#' spaced time-series data.  This package brings a few of them to R.
#' The functions describe here offer simple moving
#' average, or SMA, for short. Three variants are provides considering
#' the last or next observation relative to time \sQuote{t}, as well as
#' linear interpolation between them.
#' @title SMA functions for unevenly spaced time series
#' @param times A Datetime vector
#' @param values A numeric vector
#' @param widthbefore A double with the preceding observation width
#' @param widthafter gvA double with the subsequent observation width
#' @return A numeric vector with SMA-weighted values.
#' package at the given position is available.
#' @author Dirk Eddelbuettel for the package, Andreas Eckner for the
#' underlying code.
#' @examples
#' if (requireNamespace("xts", quietly=TRUE)) {
#'     suppressMessages(library(xts))
#'     times <- ISOdatetime(2018, 6, 7, 8, 30, 0) + c(0, 1.0, 1.2, 2.3, 2.9, 5.0)
#'     values <- seq(0, 10, by=2)
#'     plot(xts(values, order.by=times), type="b",
#'          main="Series and last/next/linear SMAs")
#'     lines(xts(SMAlast(times,values, 2.5, 1), values, order.by=times), 
#'          type="b", col="lightblue")
#'     lines(xts(SMAnext(times,values, 2.5, 1),  values, order.by=times),
#'          type="b", col="darkblue")
#'     lines(xts(SMAlinear(times,values, 2.5, 1),  values, order.by=times),
#'          type="b", col="mediumblue")
#'     addLegend("topleft", legend.names=c("series", "SMAlast", "SMAnext", "SMAlinear"),
#'               lty=rep(1,4), lwd=rep(1,4),
#'               col=c("black", "lightblue", "darkblue", "mediumblue"))
#' }
SMAnext <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_SMAnext`, times, values, widthbefore, widthafter)
}

#' @rdname SMAnext
SMAlast <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_SMAlast`, times, values, widthbefore, widthafter)
}

#' @rdname SMAnext
SMAlinear <- function(times, values, widthbefore, widthafter) {
    .Call(`_RcppUTS_SMAlinear`, times, values, widthbefore, widthafter)
}

#' The UTS library by Andreas Eckner provides algorithms for unevenly
#' spaced time-series data.  This package brings a few of them to R.
#' This function shows the original example.
#' @title Irregularly spaced time series example
#' @return Nothing
#' @author Dirk Eddelbuettel for the package, Andreas Eckner for the
#' underlying code.
#' @examples
#' utsExample()
utsExample <- function() {
    invisible(.Call(`_RcppUTS_utsExample`))
}

