# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The UTS library by Andreas Eckner provides algorithms for unevenly
#' sampled time-series data.  This package brings a few of them to R;
#' and these functions offer exponentially-decaying weighted moving
#' average, or EMA, for short. Three variants are provides considering
#' the last or next observation relative to time \sQuote{t}, as well as
#' linear interpolation between them.
#' @title EMA functions for irregularly samples time series
#' @param times A Datetime vector
#' @param values A numeric vector
#' @param tau A double with the decay factor
#' @return A numeric vector with EMA-weighted values.
#' package at the given position is available.
#' @author Dirk Eddelbuettel for the package, Andreas Eckner for the
#' underlying code.
#' @examples
#' tt <- Sys.time() + c(0, 0.2, 1.2, 2.3)
#' vv <- 0:3
#' EMAnext(tt, vv, 1)
#' EMAlast(tt, vv, 1)
#' EMAlinear(tt, vv, 1)
EMAnext <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAnext`, times, values, tau)
}

#' @rdname EMAnext
EMAlast <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAlast`, times, values, tau)
}

#' @rdname EMAnext
EMAlinear <- function(times, values, tau) {
    .Call(`_RcppUTS_EMAlinear`, times, values, tau)
}

main_example <- function() {
    .Call(`_RcppUTS_main_example`)
}

